- src: arillso.motd
- src: ericsysmin.gcloud
- src: geerlingguy.adminer
- src: geerlingguy.ansible
- src: geerlingguy.awx
- src: geerlingguy.backup
- src: geerlingguy.certbot
- src: geerlingguy.docker/
- src: geerlingguy.git/
- src: geerlingguy.glusterfs/
- src: geerlingguy.haproxy/
- src: geerlingguy.java/
- src: geerlingguy.jenkins/
- src: geerlingguy.nfs/
- src: geerlingguy.nginx/
- src: geerlingguy.nodejs/
- src: geerlingguy.ntp/
- src: geerlingguy.packer/
- src: geerlingguy.php/
- src: geerlingguy.php-mysql/
- src: geerlingguy.pip/
- src: geerlingguy.postfix/
- src: geerlingguy.postgresql/
- src: geerlingguy.puppet/
- src: geerlingguy.rabbitmq/
- src: geerlingguy.redis/
- src: geerlingguy.repo-epel/
- src: geerlingguy.repo-remi/
- src: geerlingguy.ruby/
- src: geerlingguy.supervisor/
- src: manala.influxdb/
- src: rossmcdonald.influxdb/
- src: chasinglogic.podman
- src: yatesr.timezone
